version: '3'

services:
  web:
    build:
        dockerfile: ApiDockerfile
        context: .
    ports:
      - "49160:8080"
    links:
      - db


  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./dump/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: uruit_rps
      MYSQL_USER: uruit
      MYSQL_PASSWORD: uruit_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
volumes:
    db_data: {}